### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by TWME-TW** [whimxiqal/journey#17]
A new tool has been added that allows you to set a one-time start/end point by left/right click.

Command:
- `/journey tool`
Get tool

Permissions
- `journey.command.tool`
Whether to automatically calculate the path？
- `journey.command.tool.autocalculation`

Maybe need to add a cooldown.

config.yml
`cooldown-time: <number>`
(Second 

English is not my language, so please forgive me if it means weird

**Comment by TWME-TW** [comment]
Detect multiple parkour maps at the same time in multiple people and multiple worlds

**Comment by pietelite** [comment]
Can you elaborate more on the way this would work? Is the tool for an administrator to designate a certain path, like a parkour map path, from some start to some end or do you just want a tool to run a path calculation from start to finish as though you would use the `/journey to` command to some destination?

**Comment by TWME-TW** [comment]
use the /journey to command to some destination🤔

**Comment by whimxiqal** [comment]
The plugin has changed a lot since you've used it, so I'll close the ticket for now since I don't believe this kind of enhancement would suit the existing version. 

If you have any other suggestions, or would like to revisit this idea, please make a new issue.
