### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by whimxiqal** [whimxiqal/journey#20]
Add language support

**Comment by J0J0HA** [comment]
If this will be implemented, I can do German.
(If you are not german yourself, I had that already...)
It is one of the only things I can do for plugins, since I'm mainly a Python developer.

**Comment by whimxiqal** [comment]
@J0J0HA thank you! It likely won't be implemented until there's particular demand for a non-English language, but I'll keep you updated when I'm ready for translation!

**Comment by whimxiqal** [comment]
German and Chinese has been added in v1.2. @J0J0HA if you are still interested in helping out, please check the German translation and adjust anything that looks wrong (I just used Google Translate)
