### ISSUE TITLE
Re-enable MySQL support

### ISSUE THREAD

**Issue by whimxiqal** [whimxiqal/journey#30]
MySQL support was removed for the first official release because it was untested. Once tested, and fixed if broken, MySQL can be re-enabled.

**Comment by tarunsamanta2k20** [comment]
@whimxiqal how to add Mysql support?

**Comment by whimxiqal** [comment]
The commented-out code referencing "MySQL" just has to be uncommented and then it has to be tested with a real MySQL database, which I haven't done yet.

Do you need it for your server?

**Comment by whimxiqal** [comment]
Added for v1.1
