### ISSUE TITLE
Walls and Fences are counted as 1 block tall.

### ISSUE THREAD

**Issue by TheDeafCreeper** [whimxiqal/journey#35]
Walls and (im assuming) fences appear to be counted as 1 block tall.

![2023-05-05_10 15 04](https://user-images.githubusercontent.com/34897909/236499735-7ab151b9-6952-4c09-a81c-069b9dd5f7ad.png)

**Comment by whimxiqal** [comment]
Yeah... Good point.

Slabs, trapdoors, and other half-sized or just weird shaped blocks are just badly handled. There's not a good generalized way to handle everything without doing complicated bounding box calculations that I just never deemed important enough.

But walls and fences (thing bigger than a 1x1 block in general) should definitely be handled specially. A good rule of thumb I've been following is to always keep the algorithm more restrictive than relaxed, so it can't always find possible routes but it'll never find and display an impossible route.

Currently, this violates that.
