### ISSUE TITLE
Lag spike after long path is calculated.

### ISSUE THREAD

**Issue by TheDeafCreeper** [whimxiqal/journey#37]
Strangest part is that according to spark, TPS dips but MSPT does not spike.

It also does not appear to be the plugin creating the path as the particles already exist when it starts lagging, maybe it's when it cleans up stuff?

(Relevant Spark Timing)
![image](https://github.com/whimxiqal/journey/assets/34897909/5f7ca45d-ae50-4f53-8c01-4dc6fbd14a06)

Server Version: git-Purpur-1838 (MC: 1.19.2)
Plugin Version: 1.0.2

**Comment by whimxiqal** [comment]
Looks like there's lots of time used when sending the path data to the cache database. Idk why that's scheduled on the main thread. This would also be fixed with #33 with better parallelization in general and, although not as relevant here, database pooling

**Comment by whimxiqal** [comment]
The database call is made async now with #47 for v1.1
