### ISSUE TITLE
Search fails  to start when standing over edge of block.

### ISSUE THREAD

**Issue by TheDeafCreeper** [whimxiqal/journey#48]
Example here:

![2023-05-27_23 20 27](https://github.com/whimxiqal/journey/assets/34897909/cc8f75f6-f61e-4ecf-9721-25f0ed983e0b)

Destination is the gold block, but search fails after a second even though its 10 blocks away in a straight line.

Edit: Also, the -animate flag shows nothing.

**Comment by whimxiqal** [comment]
fixed by #64
