### ISSUE TITLE
Update to 1.20.6 and 1.21

### ISSUE THREAD

**Issue by VentureStudios** [whimxiqal/journey#87]
Hello, please update plugin to 1.20.6 and 1.21

**Comment by VentureStudios** [comment]
Update to 1.20.6 and 1.21, please.

**Comment by VentureStudios** [comment]
Hey news?

**Comment by VentureStudios** [comment]
Please!

**Comment by whimxiqal** [comment]
1.20.6 and 1.21 update is underway, among other changes detailed on the Discord server. Estimated release is August 30th

**Comment by VentureStudios** [comment]
Okay

**Comment by whimxiqal** [comment]
Completed with #88
