### ISSUE TITLE
The particles are not working properly

### ISSUE THREAD

**Issue by VentureStudios** [whimxiqal/journey#89]
CI'm using the latest version of the plugin and 1.21.1.

When I start the GPS the particles don't appear if I put colours in addition to the default ones or other types of particles.

![image](https://github.com/user-attachments/assets/d9d2e628-5468-482c-82d8-aa05b47cce11)
![image](https://github.com/user-attachments/assets/753405b2-04fe-4ad6-b42d-424f11641aa7)

**Comment by whimxiqal** [comment]
This is actually easily fixable. In newer Minecraft versions, the particle for redstone dust changed from `redstone` to `dust`. Simply change the particle type in your config from `redstone` to `dust` and that should solve the problem.

**Comment by whimxiqal** [comment]
Reopening for work to be backwards-compatible with earlier configs and change the default config
